#! /bin/bash

set -x

mkdir -p tmpl
cd tmpl
# Unzip tar files from all replicas
for file in `ls ../lesson-content*/lessons.tar` ; do
    tar xf $file
    cp syntax.* ../
done
cat _data/lessons*.yml > ../lessons.yml
