#! /bin/bash

set -x

GIT_OWNER=plumed-school
GIT_REPO=plumed-school

if [[ "${GITHUB_REF##*/}" = main ]]; then
  PUSH_REPO=plumed-school/plumed-school.github.io.git
fi

hash=$(git log -1 --format="%h")

root="$PWD"
tar cfv all.tar "$@"
#tar cf all.tar -T - # list of files from stdin
mkdir -p tmp-testSite

cd tmp-testSite || exit 1

tar xf "${root}/all.tar"
# Unzip tar files from all replicas
for file in "${root}"/lesson-content*/lessons.tar; do
  tar xf "$file"
done
cat _data/lessons*.yml >_data/lessons.yml
cat _data/actionlist*.yml >_data/actionlist.yml
cp "${root}/summarygraph.md" .

export GIT_BOT_EMAIL=giovanni.bussi+plumedbot@gmail.com

# cp $root/nest.png .
# cp $root/pigeon.png .
cp "${root}/CNAME" .

if [[ "${GITHUB_REF##*/}" = main ]]; then
  # create README.md
  cat >README.md <<EOF

Welcome to PLUMED-TUTORIALS!
-----------------------------

EOF

  # add general informations
  cat Info.md >>README.md
  git init
  git config user.email giovanni.bussi+plumedbot@gmail.com
  git config user.name plumedbot
  git remote add origin https://plumedbot:$PLUMED_SCHOOL_GITHUB_TOKEN@github.com/$PUSH_REPO
  git add --all .
  # >/dev/null to avoid excessive noise on travis log
  git commit -m "Update to @$hash" >/dev/null
  # -q and 2> is not to show the PLUMED_SCHOOL_GITHUB_TOKEN log
  git push -f origin master 2>/dev/null
else
  # create README.md
  cat >README.md <<EOF

# Welcome to the test for plumed School! (commit $hash)

EOF

  # add general informations
  cat Info.md >>README.md

  sed "s/PLUMED-SCHOOL/PLUMED-SCHOOL-TEST-SITE/" _config.yml >_config.yml.tmp
  mv _config.yml.tmp _config.yml
  rm CNAME
  echo "branch ${GITHUB_REF##*/}, skipping push"
fi
