#! /bin/bash

set -x

hash=$(git log -1 --format="%h")

root="$PWD"
tar cfv all.tar "$@"
#tar cf all.tar -T - # list of files from stdin
mkdir -p tmp-testSite

cd tmp-testSite || exit 1

tar xf "${root}/all.tar"
# Unzip tar files from all replicas
for file in "${root}"/lesson-content*/lessons.tar; do
  tar xf "$file"
done
cat _data/lessons*.yml >_data/lessons.yml
cat _data/actionlist*.yml >_data/actionlist.yml
cp "${root}/summarygraph.md" .

# create README.md
cat >README.md <<EOF

# Welcome to the test for plumed School! (commit $hash)

EOF

# add general informations
cat Info.md >>README.md

# cp $root/nest.png .
# cp $root/pigeon.png .
cp "${root}/CNAME" .

# if [[ "${GITHUB_REF##*/}" = test ]]; then
sed "s/PLUMED-SCHOOL/PLUMED-SCHOOL-TEST-SITE/" _config.yml >_config.yml.tmp
mv _config.yml.tmp _config.yml
rm CNAME
# fi
