#! /bin/bash

WHAT=$1

set -x

GIT_OWNER=plumed-school
GIT_REPO=plumed-school

if [[ "${GITHUB_REF##*/}" = main ]] ; then
  PUSH_REPO=plumed-school/plumed-school.github.io.git
elif [[ "${GITHUB_REF##*/}" = test ]] ; then
  PUSH_REPO=plumed-school/test-site.git
else
  echo "branch ${GITHUB_REF##*/}, skipping push"
  exit 0
fi

hash=$( git log -1 --format="%h")

root="$PWD"
mkdir -p tmp/$$

tar cf all.tar $@
#tar cf all.tar -T - # list of files from stdin

cd tmp/$$
tar xf ../../all.tar
# Unzip tar files from all replicas
for file in `ls ../../lesson-content*/lessons.tar` ; do
    tar xf $file
done
cat _data/lessons*.yml > _data/lessons.yml
cat _data/actionlist*.yml > _data/actionlist.yml
cp ../../summarygraph.md .

export GIT_BOT_EMAIL=giovanni.bussi+plumedbot@gmail.com

git init
git config user.email giovanni.bussi+plumedbot@gmail.com
git config user.name plumedbot
git remote add origin https://plumedbot:$PLUMED_SCHOOL_GITHUB_TOKEN@github.com/$PUSH_REPO

# create README.md
cat > README.md << EOF
Welcome to PLUMED-TUTORIALS!
-----------------------------

EOF

# add general informations
cat Info.md >> README.md

# test Youtube update
python $root/count-views.py

# cp $root/nest.png .
# cp $root/pigeon.png .
cp $root/CNAME .

if [[ "${GITHUB_REF##*/}" = test ]] ; then
  sed "s/PLUMED-SCHOOL/PLUMED-SCHOOL-TEST-SITE/" _config.yml > _config.yml.tmp
  mv _config.yml.tmp _config.yml
  echo "baseurl: /test-site" >> _config.yml
  rm CNAME
fi

git add --all .
# >/dev/null to avoid excessive noise on travis log
git commit -m "Update to @$hash" >/dev/null
# -q and 2> is not to show the PLUMED_SCHOOL_GITHUB_TOKEN log
git push -f origin master 2> /dev/null 
